### ISSUE TITLE
Hiragana and Katagana characters are overlapping in CSS vertical writing-mode

### ISSUE THREAD

**Issue by YoonALover** [googlefonts/zen-kakugothic#3]

**Comment by aaronbell** [comment]
Thanks. This has been corrected with the latest update (see https://github.com/googlefonts/zen-kakugothic/tree/main/fonts/ttf)

**Comment by satoshionoda** [comment]
@aaronbell 

This issue still exists.
Could you look into this?

https://codepen.io/satoshionoda/pen/XWVJjbJ

**Comment by aaronbell** [comment]
@satoshionoda the updated font is still in Google’s sandbox apparently. Hopefully it can be pushed out soon.

**Comment by satoshionoda** [comment]
@aaronbell 

Thank you for the quick response.

It's been already two months since you pushed the fix.
Do you know how long it takes to get released from Google's sandbox?

**Comment by aaronbell** [comment]
@satoshionoda There's some processes they use to track and push fonts live and the font was missed. Unfortunately I have no idea when they will push it up, but I'd expect in the next month for sure.

**Comment by satoshionoda** [comment]
@aaronbell 

Thanks, that's good to know.
I'll keep eye on my CodePen project until the fix is released.
